services:
    backend:
        container_name: backend
        build: backend
        restart: always
        environment:
            - TZ=Europe/Paris
        networks:
            - app_network
        volumes:
            - ./backend_data:/data

    frontend:
        container_name: frontend
        build:
            context: front
        restart: always
        depends_on:
            - backend
        environment:
            - TZ=Europe/Paris
        ports:
            - 3000:80
        networks:
            - app_network
            - app_network_web
  

networks:
    app_network:
        driver: bridge
    app_network_web:
        driver: bridge
